### ISSUE TITLE
Prio 1: Requirement for .git repository

### ISSUE THREAD

**Issue by kdadzis** [nemocrys/multilog#43]
Currently program can be started, but pressing "Start" to begin data saving produces an error if the base folder is not a clone of the git repository. I.e., downloading the code from github is not sufficient and git software is needed to update the code on every PC running it. An option to skip this or enter the missing information (program version?) manually would be useful here.

**Comment by arvedes** [comment]
A related bug has been fixed with #40. Did this issue cause multilog to stop, or was it just a message in the command line/logfile?

It shouldn't be an error but just a warning, according to #40. But maybe the backtrace of the corresponding `FileNotFoundError` being caught is confusing. I think we can remove it.

**Comment by kdadzis** [comment]
Problem noch vorhanden und echt nervig. Sollte behoben werden.

---

fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/nemocrys/Documents/experiments/2025-06-23_Nemo-1_CameraTest/multilog-main/multilog/view/main_window.py", line 126, in btn_start_click
    self.start_function()
  File "/home/nemocrys/Documents/experiments/2025-06-23_Nemo-1_CameraTest/multilog-main/multilog/main.py", line 338, in start
    self.init_output_files()
  File "/home/nemocrys/Documents/experiments/2025-06-23_Nemo-1_CameraTest/multilog-main/multilog/main.py", line 385, in init_output_files
    self.write_nomad_file()
  File "/home/nemocrys/Documents/experiments/2025-06-23_Nemo-1_CameraTest/multilog-main/multilog/main.py", line 400, in write_nomad_file
    subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--dirty', '--always']' returned non-zero exit status 128.

**Comment by kdadzis** [comment]
Für das Issue nicht relevant, aber sollte hier trotzdem korrekt stehen: aktuell ist nur eine Basler Cam an Nemo-1 angeschlossen. Wo wurde der Test durchgeführt?
